crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin


app_name = 'crm'


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^opportunities/', include('opportunity.urls', namespace='opportunities')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^leads/', include('leads.urls', namespace='leads')),
    url(r'^cases/', include('cases.urls', namespace='cases')),
    url(r'^emails/', include('emails.urls', namespace='emails')),
    url(r'^user/', include('user.urls', namespace='user')),
    # url(r'^planner/', include('planner.urls', namespace='planner')),
    #url(r'^logout/$', views.logout, {'next_page': '/login/'}, name='logout'),

]

leads/urls.py
from django.conf.urls import url
from leads import views

app_name = 'leads'


urlpatterns = [
    url(r'^list/$', views.leads_list, name='list'),
    url(r'^create/$', views.add_lead, name='add_lead'),
    url(r'^(?P<lead_id>\d+)/view/$', views.view_lead, name="view_lead"),
    url(r'^(?P<lead_id>\d+)/edit/$', views.edit_lead, name='edit_lead'),
    url(r'^(?P<lead_id>\d+)/delete/$', views.remove_lead, name="remove_lead"),
    url(r'^(?P<pk>\d+)/convert/$', views.leads_convert, name='leads_convert'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
    url(r'^get/list/$', views.get_leads, name='get_lead'),
]

cases/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User

from accounts.models import Account
from contacts.models import Contact
from common.models import Team
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE


class Case(models.Model):
    name = models.CharField(pgettext_lazy("Name of the case", "Name"), max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(choices=CASE_TYPE, max_length=255, blank=True, null=True, default='')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    # contacts = models.IntegerField()
    contacts = models.ManyToManyField(Contact)
    closed_on = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    # assigned_to = models.IntegerField()
    assigned_to = models.ManyToManyField(User, related_name='case_assigned_users')
    # teams = models.IntegerField()
    teams = models.ManyToManyField(Team)
    # created_by = models.IntegerField()
    created_by = models.ForeignKey(User, related_name='case_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting", status="Planned")

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Task", status="Planned")

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task").exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Call", status="Planned")

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from common.utils import COUNTRIES

class Address(models.Model):
    address_line = models.CharField(_("Address"), max_length=255, blank=True, null=True)
    street = models.CharField(_("Street"), max_length=55, blank=True, null=True)
    city = models.CharField(_("City"), max_length=255, blank=True, null=True)
    state = models.CharField(_("State"), max_length=255, blank=True, null=True)
    postcode = models.CharField(_("Post/Zip-code"), max_length=64, blank=True, null=True)
    country = models.CharField(max_length=3, choices=COUNTRIES, blank=True, null=True)

    def __str__(self):
        return self.city


class Team(models.Model):
    name = models.CharField(max_length=55)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Comment(models.Model):
    case = models.ForeignKey('cases.Case', blank=True, null=True, related_name="cases", on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    commented_on = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    lead = models.CharField(max_length=255)
    opportunity = models.CharField(max_length=255)
    account = models.ForeignKey('accounts.Account', blank=True, null=True, related_name="accounts_comments", on_delete=models.CASCADE)
    lead = models.ForeignKey('leads.Lead', blank=True, null=True, related_name="leads", on_delete=models.CASCADE)
    opportunity = models.ForeignKey('opportunity.Opportunity', blank=True, null=True, related_name="opportunity_comments", on_delete=models.CASCADE)
    contact = models.ForeignKey('contacts.Contact', blank=True, null=True, related_name="contact_comments", on_delete=models.CASCADE)

    def get_files(self):
        return Comment_Files.objects.filter(comment_id=self)


class Comment_Files(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now_add=True)
    comment_file = models.FileField("File", upload_to="comment_files", default='')

    def get_file_name(self):
        if self.comment_file:
            return self.comment_file.path.split('/')[-1]
        else:
            return None

leads/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _

from accounts.models import Account
from django.contrib.auth.models import User
from common.models import Address, Team
from common.utils import LEAD_STATUS, LEAD_SOURCE


class Lead(models.Model):
    title = models.CharField(
        pgettext_lazy("Treatment Pronouns for the customer", "Title"),
        max_length=64, blank=True, null=True)
    first_name = models.CharField(("First name"), max_length=255)
    last_name = models.CharField(("Last name"), max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True, blank=True)
    account = models.ForeignKey(Account, related_name='Leads', on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(_("Status of Lead"), max_length=255,
                              blank=True, null=True, choices=LEAD_STATUS)
    source = models.CharField(_("Source of Lead"), max_length=255,
                              blank=True, null=True, choices=LEAD_SOURCE)
    address = models.ForeignKey(Address, related_name='leadaddress', on_delete=models.CASCADE, null=True, blank=True)
    website = models.CharField(_("Website"), max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='lead_assigned_users')
    teams = models.ManyToManyField(Team)
    account_name = models.CharField(max_length=255, null=True, blank=True)
    opportunity_amount = models.DecimalField(
        _("Opportunity Amount"), decimal_places=2, max_digits=12,
        blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)
    enquery_type = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering =['-created_on']

    def __str__(self):
        return self.first_name + self.last_name

leads/forms.py
from django import forms
from leads.models import Lead
from common.models import Comment


class LeadForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        super(LeadForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        if self.data.get('status') == 'converted':
            self.fields['account_name'].required = True
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        self.fields['phone'].required = False
        self.fields['first_name'].widget.attrs.update({
            'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update({
            'placeholder': 'Last Name'})
        self.fields['account_name'].widget.attrs.update({
            'placeholder': 'Account Name'})

    class Meta:
        model = Lead
        fields = ('assigned_to', 'teams', 'first_name', 'last_name', 'account_name', 'title',
                  'phone', 'email', 'status', 'source', 'website', 'address', 'description'
                  )

    def clean_phone(self):
        client_phone = self.cleaned_data.get('phone', None)
        if client_phone:
            try:
                if int(client_phone) and not client_phone.isalpha():
                    ph_length = str(client_phone)
                    if len(ph_length) < 10 or len(ph_length) > 13:
                        raise forms.ValidationError('Phone number must be minimum 10 Digits and maximum 13 Digits')
            except (ValueError):
                raise forms.ValidationError('Phone Number should contain only Numbers')
            return client_phone


class LeadCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'lead', 'commented_by')

leads/templates/leads/leads.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- heading_create starts here -->
  <div class="row marl heading_create">
    <div class="heading col-md-12">
     <div class="no-gutters row">
      <div class="col-md-6">
        <h4>Leads</h4>
      </div>
      <div class="col-md-6">
        <div class="create_new text-right">
          <a href="{% url 'leads:add_lead'%}"><i class="fa fa-plus"></i> Add New Lead</a>
        </div>
        </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="filter_row row marl">
    <div class="col-md-12">
      <div class="card">

        <form id="leads_filter" action="" method="POST">{%csrf_token%}
          <div class="card-body ">
            <div class="card-title">Filters</div>
            <div class="row marl">
              <div class="filter_col col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail1">First Name</label>
                  <input type="text" class="form-control" placeholder="First Name" name="first_name" value="{{request.POST.first_name}}">
                </div>
              </div>
              <div class="filter_col col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail1">Last Name</label>
                  <input type="text" class="form-control" placeholder="Last Name" name="last_name" value="{{request.POST.last_name}}">
                </div>
              </div>
              <div class="filter_col col-md-4">
                <div class="form-group">
                  <label for="exampleInputEmail1">Lead Status</label>
                  <select class="form-control" id="id_status" name="status" >
                    <option value="">--Status of Lead--</option>
                    {% for each_status in status %}
                    <option value="{{each_status.0}}" {% if request.POST.status %} {% ifequal each_status.0 request.POST.status %}selected{% endifequal %}{% endif %} >{{each_status.1}} </option>
                    {% endfor%}
                  </select>
                </div>
              </div>
              <div class="filter_col text-center col-12">
                <div class="form-group buttons_row">
                  <button class="btn btn-primary save" type="submit">Search</button>
                  <a href="{% url 'leads:list' %}" class="btn btn-default clear">Clear</a>
                </div>
              </div>
            </div>
          </div>
        </form>
        <br clear="all">
      </div>
    </div>
  </div>
  <!-- filter_row ends here -->
  <!-- leads list start-->
  <div class="table_container_row row marl">
    <div class="col-md-12">
      <div class="card">

        <div class="card-body">
          <div class="card-title">
            List of Leads
            <span class="float-right total_count">{% if show_pageitems %} {{ show_pageitems }}{% else %}Total Leads {{ lead_obj|length }}{% endif %}</span>
            </div>
            <div class="table-responsive">
              <table class="table table-bordered table-striped table-condensed">
                <thead>
                 <tr>
                    <th width="5%" style="text-align:center;">S.no</th>
                    <th width="20%" style="text-align:center;">Name</th>
                    <th width="15%" style="text-align:center;">Status</th>
                    <th width="15%" style="text-align:center;">Assigned User</th>
                    <th width="20%" style="text-align:center;">Created On</th>
                    <th width="25%" style="text-align:center;">Actions</th>
                  </tr>

                </thead>
                <tbody>
                  {% for lead in lead_obj %}
                  <tr class="text-center">
                    <td scope="row">{{ forloop.counter }}</td>
                    <td><a href="{% url 'leads:view_lead' lead.id %}">{{ lead.first_name }} {{ lead.last_name }}</a></td>
                    <td>{{ lead.status }}</td>
                    <td>
                      {% with lead_users=lead.assigned_to.all %}
                        {% if lead_users %}
                          {% for user in lead_users %}
                            <li class="text-left">{{ user.email }}</li>
                          {% endfor %}
                        {% else %}
                          Not Assigned to Any
                        {% endif %}
                      {% endwith %}
                    </td>
                    <td>{{ lead.created_on }}</td>
                    <td class="actions">
                      <a href="{% url 'leads:view_lead' lead.id %}" class="btn btn-info view"><i class="fas fa-eye"></i> View</a>
                      <a href="{% url 'leads:edit_lead' lead.id %}" class="btn btn-success edit"><i class="fas fa-pencil-alt"></i>Edit</a>
                      <a href="{% url 'leads:remove_lead' lead.id %}" class="btn btn-danger delete remove_account"><i class="fas fa-trash"></i>Delete</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            {%ifequal lead_obj|length 0%}
              <h6 class="text-center">No Lead Records Found</h6>
            {%endifequal%}
            <div class="text-center row marl">
                {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="page-item disabled"><a class="page-link" href="?page=1">&laquo;</a></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                      {% else %}
                        <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
                    {% endif %}
                  </ul>
                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- leads list end-->
</div>
<!-- main_container ends here -->
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $('.delete').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function(e){
    e.preventDefault();
    $('#leads_filter').attr("action", $(this).attr("href"));
    $('#leads_filter').submit();
  });
</script>
{% endblock js_block %}

leads/templates/leads/view_leads.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'leads:list' %}">Leads</a></li>
    <li class="breadcrumb-item active">View</li>
  </ol>
</nav>

{%endblock%}
{% block content %}
<div class="main_container" id="maincontainer">
  <div class="overview_form_block row marl">
    <div class="col-md-8">
      <div class="card">

        <div class="card-body" id="datashow">
         <div class="card-title">
          <h5>
            Overview
            <span class="float-right" style="margin-top: 0px">
              <div class="dropdown buttons_row">
                <button class="btn btn-primary dropdown-toggle save" type="button" data-toggle="dropdown">Actions
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'leads:edit_lead' lead_record.id %}" >Edit</a></li>
                  <li class="delete_contact" ><a href="{% url 'leads:remove_lead' lead_record.id %}" id="remove_contact">REMOVE</a></li>
                  <li><a href="{% url 'leads:leads_convert' lead_record.id %}" class="btn btn-info" role="button">Convert</a></li>
                </ul>
              </div>
            </span>
          </h5>
        </div>
          <div class="row marl">
            <div class="col-md-6">
              <div class="filter_col col-md-12" id="iname">
                <div class="form-group" >
                  <label class="lead_field_label" for="id_name" data-name="name">Name</label>
                  <div class="lead_field" id="lead_name" data-name="name">{{ lead_record.first_name }} {{ lead_record.last_name }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.account_name %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_contact_account" data-name="name">Account Name</label>
                  <div class="lead_field" id ="contact_account" data-name="name">{{ lead_record.account_name }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.title %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_title" data-name="name">Title</label>
                  <div class="lead_field" id="lead_title" data-name="name">{{ lead_record.title }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="lead_field_label" for="id_phone" data-name="name">Phone</label>
                  <div class="lead_field" id="lead_phone" data-name="name">{{ lead_record.phone }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="lead_field_label" for="id_email" data-name="name">Email</label>
                  <div class="lead_field" id="lead_email" data-name="name">{{ lead_record.email }}</div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="filter_col col-md-12">
                {% if lead_record.status %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_status" data-name="name">Status</label>
                  <div class="lead_field" id="lead_status" data-name="name">{{ lead_record.status }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.source %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_source" data-name="name">Source</label>
                  <div class="lead_field" id="lead_source" data-name="name">{{ lead_record.source }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.website %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_website" data-name="name">Website</label>
                  <div class="lead_field" id="lead_website" data-name="name">{{ lead_record.website }}</div>
                </div>
                {% endif %}
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  {% if lead_record.address.address_line or lead_record.address.street or lead_record.address.city or lead_record.address.state or lead_record.address.postcode or lead_record.address.country %}
                  <label class="lead_field_label" for="id_address" data-name="name" >Billing Address</label>
                  <div class="lead_field" id="lead_address" data-name="name">
                    {% if lead_record.address.address_line %}
                      Address Line:{{lead_record.address.address_line}}</br>
                    {% endif %}
                    {% if lead_record.address.street %}
                      Street:{{ lead_record.address.street }}</br>
                    {% endif %}
                    {% if lead_record.address.city %}
                      City: {{ lead_record.address.city }}</br>
                    {% endif %}
                    {% if lead_record.address.state %}
                      State:{{ lead_record.address.state }}</br>
                    {% endif %}
                    {% if lead_record.address.postcode %}
                      Post Code:{{ lead_record.address.postcode }}</br>
                    {% endif %}
                    {% if lead_record.address.country %}
                      Country: {{ lead_record.address.get_country_display }}
                    {% endif %}
                  </div>
                  {% endif %}
                </div>
              </div>
              <div class="filter_col col-md-12">
                {% if lead_record.description %}
                <div class="form-group">
                  <label class="lead_field_label" for="id_description" data-name="name" >Description</label>
                  <div class="lead_field" id="lead_description" data-name="name">{{ lead_record.description }}</div>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <!-- Comments Section starts-->

        <div class="card-body mar-top" id="datashow">
         <div class="card-title view-pad">
          <h5>Comments </h5>
        </div>
          <div class="row marl">
            <div class="col-md-12">
              <form id="comment_form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-group ">
                  <textarea class="form-control" textarea cols="40" rows="3" id="id_comments" name="comment" placeholder="Submit Your Comments Here"></textarea><span><i id="CommentError" style="display:none; color:red"></i></span>
                  </br>
                  <div class="buttons_row">
                  <button class="btn btn-default save" style="text-align: center;" id="comment_submit">Submit</button>
                  </div>
                </div>
                <input type="hidden" value="{{lead_record.id}}" name="leadid">
              </form>
              <ul class="list-group" id="comments_div">
                {% for comment in comments %}
                <li class="list-group-item list-row" id="comment{{comment.id}}">
                  <div class="pull-right right-container">
                    <div class="list-row-buttons btn-group pull-right">
                      <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
                      <ul class="dropdown-menu pull-right">
                        <li>
                          <a class="action" onclick="edit_comment({{comment.id}})">Edit</a>
                        </li>
                        <li>
                          <a class="action" onclick="remove_comment({{comment.id}})">Remove</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="stream-head-container">{{ comment.commented_by }} Commented</div>
                  <div class="stream-post-container" id="comment_name{{comment.id}}"><pre>{{ comment.comment }}</pre></div>
                  <div class="stream-date-container">{{ comment.commented_on }}</div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="modal fade" id="Comments_Leads_Modal" role="dialog" data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Update Your Comment</h4>
                </div>
                <form id="comment_edit_form" method="POST" >{% csrf_token %}
                  <div class="modal-body">
                    <div class="form-group">
                      <textarea class="form-control" textarea cols="40" rows="3" id="id_editcomment" name="comment" placeholder="Submit Your Comments"></textarea><span><i id="CommentEditError" style="display:none; color:red"></i></span>
                      <input type="hidden" value="{{ lead.id }}" name="leadid">
                      <input type="hidden" value="" name="commentid" id="commentid">
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button class="btn btn-default save" id="comment_edit" type="submit">Update</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- Comments Section Ends-->
      </div>
    </div>
    <tr id="meeting{{ meeting.id }}">
    <div class="col-md-4">
      <div class="card">

        <div class="card-body" id="datashow">
         <div class="card-title">
          <h5>Label</h5>
        </div>
          <div class="row marl">
            <div class="filter_col col-md-12">
              <div class="form-group">
                <label class="lead_field_label" for="id_assigned_user" data-name="name" >Assigned User(s)</label>
                <div class="lead_field" id="lead_assigned_users" data-name="name">
                  {%if not lead_record.assigned_to %}
                    Not Assigned Yet
                  {% else %}
                    {% for user in lead_record.assigned_to.all %}
                      <li>{{ user }}</li>
                    {% endfor %}
                  {% endif %}
                </div>
              </div>
            </div>
            <!-- <div class="filter_col col-md-12">
              <div class="form-group">
                <label class="lead_field_label" for="id_team" data-name="name" >Assigned Team(s)</label>
                <div class="lead_field" id="lead_team" data-name="name">
                  {%if not lead_record.teams %}
                    Not Assigned Yet
                  {% else %}
                    {% for team in lead_record.teams.all %}
                      <li>{{ team }}</li>
                    {% endfor %}
                  {% endif %}
                </div>
              </div>
            </div> -->
            <div class="filter_col col-md-12">
              <div class="form-group">
                <label class="lead_field_label" for="id_created_on" data-name="name">Created On</label>
                <div class="lead_field" id="lead_created_on" data-name="name">
                  {{lead_record.created_on}}
                </div>
              </div>
            </div>
            <div class="filter_col col-md-12">
              <div class="form-group">
                <label class="lead_field_label" for="id_created_by" data-name="name">Created by</label>
                <div class="lead_field" id="lead_created_by" data-name="name">
                  {{lead_record.created_by}}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block js_block %}
 <script src="{% static 'js/leads/view_lead.js' %}"></script>
 <script src="{% static 'js/calls.js' %}"></script>
 <script src="{% static 'js/leads/meetings.js' %}"></script>
{% endblock js_block %}