accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'


urlpatterns = [
    url(r'^list/$', views.accounts_list, name='list'),
    url(r'^create/$', views.add_account, name='new_account'),
    url(r'^(?P<account_id>\d*)/view/$', views.view_account, name="view_account"),
    url(r'^(?P<edid>\d*)/edit/$', views.edit_account, name="edit_account"),
    url(r'^(?P<aid>\d*)/delete/$', views.remove_account, name="remove_account"),
    url(r'^get/list/$', views.get_accounts, name='get_accounts'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

contacts/urls.py
from django.conf.urls import url
from contacts import views

app_name = 'contacts'


urlpatterns = [
    url(r'^list/$', views.contacts_list, name='list'),
    url(r'^create/$', views.add_contact, name='add_contact'),
    url(r'^(?P<contact_id>\d+)/view/$', views.view_contact, name='view_contact'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_contact, name='edit_contact'),
    url(r'^(?P<pk>\d+)/delete/$', views.remove_contact, name='remove_contact'),
    url(r'^get/list/$', views.get_contacts, name='get_contacts'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin


app_name = 'crm'


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^opportunities/', include('opportunity.urls', namespace='opportunities')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^leads/', include('leads.urls', namespace='leads')),
    url(r'^cases/', include('cases.urls', namespace='cases')),
    url(r'^emails/', include('emails.urls', namespace='emails')),
    url(r'^user/', include('user.urls', namespace='user')),
    # url(r'^planner/', include('planner.urls', namespace='planner')),
    #url(r'^logout/$', views.logout, {'next_page': '/login/'}, name='logout'),

]

opportunity/urls.py
from django.conf.urls import url
from opportunity import views

app_name = 'opportunity'


urlpatterns = [
    url(r'^list/$', views.opp_list, name='list'),
    url(r'^create/$', views.opp_create, name='save'),
    url(r'^(?P<pk>\d+)/view/$', views.opp_view, name='opp_view'),
    url(r'^(?P<pk>\d+)/edit/$', views.opp_edit, name='opp_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.opp_remove, name='opp_remove'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^get/list/$', views.get_opportunity, name='get_opportunity'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from common.utils import COUNTRIES

class Address(models.Model):
    address_line = models.CharField(_("Address"), max_length=255, blank=True, null=True)
    street = models.CharField(_("Street"), max_length=55, blank=True, null=True)
    city = models.CharField(_("City"), max_length=255, blank=True, null=True)
    state = models.CharField(_("State"), max_length=255, blank=True, null=True)
    postcode = models.CharField(_("Post/Zip-code"), max_length=64, blank=True, null=True)
    country = models.CharField(max_length=3, choices=COUNTRIES, blank=True, null=True)

    def __str__(self):
        return self.city


class Team(models.Model):
    name = models.CharField(max_length=55)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Comment(models.Model):
    case = models.ForeignKey('cases.Case', blank=True, null=True, related_name="cases", on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    commented_on = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    lead = models.CharField(max_length=255)
    opportunity = models.CharField(max_length=255)
    account = models.ForeignKey('accounts.Account', blank=True, null=True, related_name="accounts_comments", on_delete=models.CASCADE)
    lead = models.ForeignKey('leads.Lead', blank=True, null=True, related_name="leads", on_delete=models.CASCADE)
    opportunity = models.ForeignKey('opportunity.Opportunity', blank=True, null=True, related_name="opportunity_comments", on_delete=models.CASCADE)
    contact = models.ForeignKey('contacts.Contact', blank=True, null=True, related_name="contact_comments", on_delete=models.CASCADE)

    def get_files(self):
        return Comment_Files.objects.filter(comment_id=self)


class Comment_Files(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now_add=True)
    comment_file = models.FileField("File", upload_to="comment_files", default='')

    def get_file_name(self):
        if self.comment_file:
            return self.comment_file.path.split('/')[-1]
        else:
            return None

opportunity/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

from accounts.models import Account
from contacts.models import Contact
from common.models import Team
from common.utils import STAGES, SOURCES, CURRENCY_CODES


class Opportunity(models.Model):
    name = models.CharField(pgettext_lazy("Name of Opportunity", "Name"), max_length=64)
    account = models.ForeignKey(Account, related_name='opportunities', on_delete=models.CASCADE, blank=True, null=True)
    stage = models.CharField(
        pgettext_lazy("Stage of Opportunity", "Stage"), max_length=64, choices=STAGES)
    currency = models.CharField(max_length=3, choices=CURRENCY_CODES, blank=True, null=True)
    amount = models.DecimalField(_("Opportunity Amount"), decimal_places=2, max_digits=12, blank=True, null=True)
    lead_source = models.CharField(_("Source of Lead"), max_length=255, choices=SOURCES, blank=True, null=True)
    probability = models.IntegerField(default=0, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    closed_on = models.DateTimeField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='opportunity_assigned_to')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='opportunity_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name

opportunity/forms.py
from django import forms
from opportunity.models import Opportunity
from common.models import Comment


class OpportunityForm(forms.ModelForm):
    probability = forms.IntegerField(max_value=100, required=False)

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        opp_accounts = kwargs.pop('account', [])
        opp_contacts = kwargs.pop('contacts', [])
        super(OpportunityForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({
            'rows': '8'})
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['account'].queryset = opp_accounts
        self.fields['contacts'].queryset = opp_contacts
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        self.fields['contacts'].required = False

    class Meta:
        model = Opportunity
        fields = (
            'name', 'amount', 'account', 'contacts', 'assigned_to', 'currency',
            'probability', 'teams', 'closed_on', 'lead_source', 'description', 'stage',
        )


class OpportunityCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'opportunity', 'commented_by')

user/views.py
# from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import logout as auth_logout, authenticate as auth_authenticate, login as auth_login, \
    update_session_auth_hash
# from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms.formsets import formset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, ListView

from .forms import LoginForm, UserForm, PasswordForm, ResetPassForm, ProfileForm
from .models import Profile


# from .models import User

# TODO there is still missing things like view_user and edit_user so still some
# TODO work left for me to clean it out of the old common app


class UserLogin(View):
    """
    Class made for users to login
    """
    # TODO next not implemented
    form_class = LoginForm
    template_name = 'user/login.html'

    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(request.user.profile.get_view_url())
        context = {'form': self.form_class()}
        return render(request, self.template_name, context)

    def post(self, request):
        bound_form = self.form_class(request.POST, request=request)
        if bound_form.is_valid():
            user = auth_authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
            auth_login(request, user)
            return HttpResponseRedirect('/')
        # else:
            # context = {'form': self.form_class()}
        return render(request, self.template_name, {'form': bound_form})


class UserCreate(View):
    form_class = UserForm
    # this could be simplified with the formset_factory
    formset_password = formset_factory(PasswordForm)
    formset_profile = ProfileForm
    # users_list = User.objects.all()
    template_name = 'user/user_create_form.html'

    def get(self, request):
        context = {'form': self.form_class, 'passform': self.formset_password}
        return render(request, self.template_name, context)

    def post(self, request):
        bound_form = self.form_class(request.POST)
        password_form = self.formset_password(request.POST)
        if all([bound_form.is_valid(), password_form.is_valid()]):
            new_user = bound_form.save(commit=False)
            for inline_form in password_form:
                if inline_form.cleaned_data:
                    password = inline_form.cleaned_data
                    new_user.set_password(password)
            new_user.save()
            return redirect(new_user.profile.get_view_url())

        return render(request, self.template_name, {'form': bound_form, 'passform': password_form })


class UserUpdatePass(View):
    form_class = ResetPassForm
    # formset_class = formset_factory(PasswordForm)
    template_name = 'user/user_update_pass_form.html'

    def get(self, request):
        form = self.form_class(user=request.user)
        context = {'form': form, 'user_obj': request.user}
        return render(request, self.template_name, context)

    def post(self, request):
        bound_form = self.form_class(request.user, request.POST)
        user = get_object_or_404(User, pk=request.user.pk)
        if bound_form.is_valid():
            user = bound_form.save()
            update_session_auth_hash(request, user)  # Important!
            # not working because super().form_valid(form) is missing i think
            messages.success(request, 'Your password was successfully updated!')
            return redirect('user:me')
        else:
            messages.error(request, 'Please correct the error below.')
            return render(request, self.template_name, {'form': bound_form})


class UserList(ListView):
    """
        class view for user list
    """
    # TODO this view should only be allowed to be used for logged in personnel
    model = User
    template_name = 'user/user_list.html'
    paginate_by = 10
    queryset = User.objects.get_queryset().order_by('id')



class UserView(View):
    """
        class view for user profile
    """
    template_name = 'user/user_view.html'

    def get(self, request, user_id="N/A"):
        if user_id == "N/A":
            user = request.user
            user_obj = get_object_or_404(User, pk=user.id)
        else:
            user_obj = get_object_or_404(User, pk=user_id)

        context = {'user_obj': user_obj}
        return render(request, self.template_name, context)


class UserEdit(View):
    """
        class view for editing user
    """
    model = User
    profile_model = Profile
    form_class = UserForm
    form_profile = ProfileForm
    success_url = ''
    template_name = 'user/user_update_form.html'

    def get(self, request, user_id):
        user_obj = get_object_or_404(self.model, pk=user_id)
        profile_obj = get_object_or_404(self.profile_model, user=user_obj)
        formset = self.form_profile(instance=profile_obj)
        context = {'form': self.form_class(instance=user_obj), 'user_obj': user_obj, 'profile': formset}
        return render(request, self.template_name, context)

    def post(self, request, user_id):
        user_obj = get_object_or_404(self.model, pk=user_id)
        obj = get_object_or_404(self.model, pk=user_id)
        profile_obj = get_object_or_404(self.profile_model, pk=user_id)
        bound_form = self.form_class(request.POST, instance=obj)
        profile_form = self.form_profile(request.POST, instance=profile_obj)
        if bound_form.is_valid() and profile_form.is_valid():
            bound_form.save()
            profile_form.save()
            self.success_url = user_obj.profile.get_view_url()
            return redirect(self.success_url)
        else:
            context = {'form': bound_form, self.model.__name__.lower(): obj, 'profile': profile_form, 'user_obj': user_obj}
            return render(request, self.template_name, context)


class UserDelete(View):
    pass


@login_required
def logout(request):
    form_class = LoginForm
    context = {'form':form_class}
    template_name = "user/logged_out.html"
    auth_logout(request)
    request.session.flush()
    return render(request, template_name, context)

opportunity/templates/opportunity/create_opportunity.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'opportunities:list' %}">Opportunities</a></li>
    <li class="breadcrumb-item active">Create</li>
  </ol>
</nav>
{% endblock %}
{% block content %}
  <form class= "form_user" method="POST" action="" novalidate>{% csrf_token %}
    <!-- <div class="assigned_teams row marl">
      <div class="col-md-12">
        <div class="card">
          
          <div class="card-body">
          <div class="card-title">
            Assigned Users & Teams
          </div>
            <div class="row marl">
            <div class="filter_col col-md-6">
              <div class="form-group">
                <label for="exampleInputEmail1">Assigned Users</label>
                {{ opportunity_form.assigned_to }}
              </div>
            </div>
            <div class="filter_col col-md-6">
              <div class="form-group">
                <label for="id_teams">Teams</label>
                {{ opportunity_form.teams }}
              </div>
            </div>
            </div>
            <br clear="all">
          </div>
        </div>
      </div>
      <br clear="all">
    </div> -->
    <div class="overview_form_block row marl">
      <div class="col-md-12">
        <div class="card">
          
          <div class="card-body">
          <div class="card-title text-center">
            CREATE OPPORTUNITY
          </div>
            <div class="row marl no-gutters">
              <div class="col-md-6">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1" class="required">Name{% if opportunity_form.name.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.name }}
                    <span class="error">{{opportunity_form.name.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Account{% if opportunity_form.account.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.account }}
                    <span class="error">{{opportunity_form.account.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Amount</label>
                    <div class="input-group" style="width:100%;">
                      <div class="input-group-btn left-dropdown" style="width:auto;">
                        {{ opportunity_form.currency }}
                        <span class="error">{{opportunity_form.currency.errors}}</span>
                      </div>
                      {{ opportunity_form.amount }}
                      <span class="error">{{opportunity_form.amount.errors}}</span>
                    </div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1" class="required">Stage{% if opportunity_form.stage.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.stage }}
                    <span class="error">{{opportunity_form.stage.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Lead Source{% if opportunity_form.lead_source.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.lead_source }}
                    <span class="error">{{opportunity_form.lead_source.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Probability %{% if opportunity_form.probability.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.probability }}
                    <span class="error">{{opportunity_form.probability.errors}}</span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Assigned Users</label>
                    {{ opportunity_form.assigned_to }}
                  </div>
                </div>
                <br>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Contacts{% if opportunity_form.contacts.field.required %}<span class="error">*</span>{% endif %}</label>
                    {{ opportunity_form.contacts }}
                    <span class="error">{{opportunity_form.contacts.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Close Date{% if opportunity_form.closed_on.field.required %}<span class="error">*</span>{% endif %}</label>
                    <div class='input-group date' id='datepicker1'>
                      {{ opportunity_form.closed_on }}
                      <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                    </div>
                    <span class="error">{{opportunity_form.closed_on.errors}}</span>
                  </div>
                </div>
                <div class="form-group col-md-12">
                  <label for="exampleInputEmail1" >Description{% if opportunity_form.description.field.required %}<span class="error">*</span>{% endif %}</label>
                  {{ opportunity_form.description }}
                  <span class="error">{{opportunity_form.description.errors}}</span>
                </div>
              </div>
            </div>
            <br clear="all">
            <input type="hidden" id="save_new_form" name="savenewform">
          </div>
          <!-- overview ends here -->
          <div class="row marl buttons_row text-center form_btn_row">
            <button class=" btn btn-default save" type="submit" id="saveform">Save</button>
            {% if not opportunity_obj %}
              <button class="btn btn-success save savenew" type="submit">Save & New</button>
            {% endif %}
            <a href="{% url 'opportunities:list' %}" class="btn btn-default clear">Cancel</a>
          </div>
        </div>
      </div>
    </div>
  </form>
{% endblock %}
{% block js_block %}
  <script src="{% static 'js/opportunities/contacts.js' %}"></script>
  <script type="text/javascript">
    $(function () {
       var date = new Date();
       var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $('#id_closed_on').datetimepicker({
            'format': 'YYYY-MM-DD',
            minDate:today
        })
    });

    $(".savenew").on('click', function(e){
      e.preventDefault()
      $("#save_new_form").val('true')
      $('.form_user').submit()
    });
  </script>
{% endblock js_block %}

opportunity/templates/opportunity/opportunity.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- heading_create starts here -->
  <div class="row marl heading_create">
    <div class="heading col-md-12">
      <div class="row marl no-gutters">
        <div class="col-md-6">
          <h4>Opportunities</h4>
        </div>
        <div class="col-md-6">
          <div class="create_new text-right">
            <a href="{% url 'opportunities:save' %}"><i class="fa fa-plus"></i> Add New Opportunity</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="filter_row row marl">
    <div class="col-md-12">
      <div class="card">

        <form id="opportunity_filter" method="POST" action="">{% csrf_token %}
          <div class="card-body ">
           <div class="card-title">Filters</div>
            <div class="row marl">
              <div class="filter_col col-md-3">
                <div class="form-group">
                  <label for="exampleInputEmail1">Name</label>
                  <input type="text" class="form-control" placeholder="Name" id="id_name" name="name" {% if request.POST %} value="{{request.POST.name}}" {% endif %}>
                </div>
              </div>
              <div class="filter_col col-md-3">
                <div class="form-group">
                  <label for="exampleInputEmail1">Account</label>
                  <select class="form-control" id="id_account" name="account">
                    <option value="">---------</option>
                    {% for l in accounts %}
                    <option value="{{l.id}}" {% if request.POST.account %}{%ifequal l.id request.POST.account|add:"0"%}selected{%endifequal%} {% endif %}>{{ l.name }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <div class="filter_col col-md-3">
                <div class="form-group">
                  <label for="exampleInputEmail1">Stage</label>
                  <select class="form-control" id="id_stage" name="stage" >
                    <option value="">---------</option>
                    {% for stage in stages %}
                    <option value="{{stage.0}}" {% if request.POST.stage %} {% ifequal stage.0 request.POST.stage %}selected{% endifequal %} {% endif %}>{{stage.1}} </option>
                    {% endfor%}
                  </select>
                </div>
              </div>
              <div class="filter_col col-md-3">
                <div class="form-group">
                  <label for="exampleInputEmail1">Lead Source</label>
                  <select class="form-control" id="id_lead_source" name="lead_source" >
                    <option value="">---------</option>
                    {% for source in sources %}
                    <option value="{{source.0}}" {% if request.POST.lead_source %} {% ifequal source.0 request.POST.lead_source %}selected{% endifequal %} {% endif %}>{{source.1}} </option>
                    {% endfor%}
                  </select>
                </div>
              </div>
              <div class="filter_col text-center col-12">
                <div class="form-group buttons_row">
                  <button class="btn btn-primary save" type="submit">Search</button>
                  <a href="{% url 'opportunities:list' %}" class="btn btn-default clear">Clear</a>
                </div>
              </div>
            </div>
          </div>
        </form>
        <br clear="all">
      </div>
    </div>
  </div>
  <!-- filter_row ends here -->
  <!-- opportunities list start-->
  <div class="table_container_row row marl">
    <div class="col-md-12">
      <div class="card">

        <div class="card-body">
         <div class="panel-heading-list card-title ">
         List of Opportunities
          <span class="float-right total_count">{% if show_pageitems %} {{ show_pageitems }}{% else %}Total Opportunities {{ opportunity_list|length }}{% endif %}</span>
        </div>
        <div class="table-responsive">
          <table class="table table-bordered table-striped table-condensed">
            <thead>
              <tr>
                <th width="5%" style="text-align:center;">S.No</th>
                <th width="15%" style="text-align:center;">Name</th>
                <th width="15%" style="text-align:center;">Account</th>
                <th width="15%" style="text-align:center;">Contact(s)</th>
                <th width="15%" style="text-align:center;">Stage</th>
                <th width="10%" style="text-align:center;">Lead Source</th>
                <th width="25%" style="text-align:center;">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for opportunity in opportunity_list %}
              <tr class="text-center">
                <td scope="row">{{ forloop.counter }}</td>
                <td><a href="{% url  'opportunities:opp_view' opportunity.id %}">{{ opportunity.name }}</a></td>
                <td>
                  {% if opportunity.account %}
                    <a href="{% url  'accounts:view_account' opportunity.account.id %}">{{ opportunity.account }}</a>
                  {% else %}
                    No Related Account
                  {% endif %}
                </td>
                <td>
                  {% with opp_contacts=opportunity.contacts.all %}
                    {% if opp_contacts %}
                      {% for contact in opp_contacts %}
                        <li class="text-left"><a href="{% url 'contacts:view_contact' contact.id %}">{{contact.first_name}} {{contact.last_name}}</a></li>
                      {% endfor %}
                    {% else %}
                      No Related Contact
                    {% endif %}
                  {% endwith %}
                </td>
                <td>{% if opportunity.stage %}{{ opportunity.stage }}{% else %}Not Specified {% endif %}</td>
                <td>{% if opportunity.lead_source %}{{ opportunity.lead_source }}{% else %}Not Specified{% endif %}</td>
                <td class="actions">
                  <a href="{% url 'opportunities:opp_view' opportunity.id %}" class="btn btn-info view"><i class="fas fa-eye"></i> View</a>
                  <a href="{% url 'opportunities:opp_edit' opportunity.id %}" class="btn btn-success edit"><i class="fas fa-pencil-alt"></i>Edit</a>
                  <a href="{% url 'opportunities:opp_remove' opportunity.id %}" class="btn btn-danger delete remove_account"><i class="fas fa-trash"></i>Delete</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
          {% ifequal opportunity_list|length 0 %}
            <h6 class="text-center">No Opportunity Records Found</h6>
          {% endifequal %}
          <div class="text-center row marl">
              {% if is_paginated %}
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                  {% else %}
                    <li class="page-item disabled"><a class="page-link" href="?page=1">&laquo;</a></li>
                  {% endif %}
                  {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                      <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% else %}
                      <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                  {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
                  {% endif %}
                </ul>
              {% endif %}
          </div>
        </div>

      </div>
    </div>
    <br clear="all">
  </div>
  <!-- opportunities list end-->
</div>
<!-- main_container ends here -->
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $('.delete').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function(e){
    e.preventDefault();
    $('#opportunity_filter').attr("action", $(this).attr("href"));
    $('#opportunity_filter').submit();
  });
</script>
{% endblock js_block %}